addresses = [
    "12 Baker Street - London - UK", "45 Elm Avenue - New York - USA", "78 Oak Lane - Toronto - Canada",
    "23 Maple Drive - Sydney - Australia", "56 Pine Road - Auckland - New Zealand", "89 Cedar Court - Dublin - Ireland",
    "34 Birch Boulevard - Berlin - Germany", "67 Walnut Street - Paris - France", "90 Ash Way - Tokyo - Japan",
    "11 Chestnut Close - Mumbai - India", "44 Willow Walk - Beijing - China", "77 Poplar Place - Seoul - South Korea",
    "22 Sycamore Square - Mexico City - Mexico", "55 Magnolia Mews - São Paulo - Brazil", "88 Hazel Hill - Cape Town - South Africa",
    "33 Spruce Street - Amsterdam - Netherlands", "66 Fir Avenue - Stockholm - Sweden", "99 Beech Road - Oslo - Norway",
    "14 Laurel Lane - Copenhagen - Denmark", "47 Holly Drive - Helsinki - Finland", "80 Ivy Court - Vienna - Austria",
    "25 Rowan Boulevard - Zurich - Switzerland", "58 Alder Close - Brussels - Belgium", "91 Juniper Way - Lisbon - Portugal",
    "36 Cypress Square - Madrid - Spain", "69 Redwood Mews - Rome - Italy", "10 Palm Place - Athens - Greece",
    "43 Mango Hill - Istanbul - Turkey", "76 Bamboo Street - Bangkok - Thailand", "21 Lotus Avenue - Singapore",
    "54 Orchid Road - Kuala Lumpur - Malaysia", "87 Jasmine Drive - Jakarta - Indonesia", "32 Blossom Court - Manila - Philippines",
    "65 Petal Lane - Dhaka - Bangladesh", "98 Garden Boulevard - Karachi - Pakistan", "13 Sunrise Close - Cairo - Egypt",
    "46 Sunset Way - Nairobi - Kenya", "79 Horizon Square - Lagos - Nigeria", "24 Breeze Mews - Accra - Ghana",
    "57 Valley Place - Casablanca - Morocco", "85 Riverside Drive - Chicago - USA", "17 Lakeview Avenue - Vancouver - Canada",
    "50 Hillside Road - Melbourne - Australia", "83 Seaside Court - Wellington - New Zealand", "28 Clifftop Lane - Edinburgh - Scotland",
    "61 Moorland Boulevard - Manchester - UK", "94 Harborview Street - Hamburg - Germany", "39 Vineyard Close - Lyon - France",
    "72 Meadow Way - Osaka - Japan", "15 Mountain Square - Bangalore - India", "48 Riverside Mews - Shanghai - China",
    "81 Lakeside Place - Busan - South Korea", "26 Beachfront Drive - Cancun - Mexico", "59 Rainforest Avenue - Rio de Janeiro - Brazil",
    "92 Savanna Road - Johannesburg - South Africa", "37 Canal Court - Rotterdam - Netherlands", "70 Fjord Lane - Gothenburg - Sweden",
    "13 Tundra Boulevard - Bergen - Norway", "46 Harbor Close - Aarhus - Denmark", "79 Arctic Way - Tampere - Finland",
    "24 Alpine Square - Salzburg - Austria", "57 Glacier Mews - Geneva - Switzerland", "90 Forest Place - Ghent - Belgium",
    "35 Coastal Drive - Porto - Portugal", "68 Desert Road - Seville - Spain", "11 Volcano Avenue - Naples - Italy",
    "44 Olive Court - Thessaloniki - Greece", "77 Spice Lane - Ankara - Turkey", "22 Temple Boulevard - Chiang Mai - Thailand",
    "55 Marina Close - Penang - Malaysia", "88 Coral Way - Bali - Indonesia", "33 Pearl Square - Cebu - Philippines",
    "66 Delta Mews - Chittagong - Bangladesh", "99 Silk Place - Lahore - Pakistan", "14 Pyramid Drive - Alexandria - Egypt",
    "47 Safari Road - Mombasa - Kenya", "80 Savannah Avenue - Abuja - Nigeria", "25 Kente Court - Kumasi - Ghana",
    "58 Atlas Lane - Marrakech - Morocco", "91 Lakeshore Boulevard - Houston - USA", "36 Ridgeway Close - Calgary - Canada",
    "69 Bayside Way - Brisbane - Australia", "12 Terrace Square - Christchurch - New Zealand", "45 Cobblestone Mews - Cork - Ireland",
    "78 Cathedral Place - Birmingham - UK", "23 Promenade Drive - Munich - Germany", "56 Montmartre Road - Marseille - France",
    "89 Sakura Avenue - Kyoto - Japan", "34 Bollywood Court - Chennai - India", "67 Hutong Lane - Chengdu - China",
    "10 Hanok Way - Incheon - South Korea", "43 Aztec Boulevard - Guadalajara - Mexico", "76 Carnival Close - Brasilia - Brazil",
    "21 Zulu Square - Durban - South Africa", "54 Windmill Mews - Utrecht - Netherlands", "87 Viking Place - Malmo - Sweden",
    "32 Aurora Drive - Stavanger - Norway", "65 Lighthouse Road - Odense - Denmark", "98 Sauna Court - Turku - Finland",
]