product_catalog = {
    # Electronics
    "Wireless Earbuds": "Electronics", "Mechanical Keyboard": "Electronics",
    "USB-C Hub": "Electronics", "Noise-Cancelling Headphones": "Electronics",
    "Portable Charger": "Electronics", "Smart Watch": "Electronics",
    "Webcam HD": "Electronics", "LED Desk Lamp": "Electronics",
    "Gaming Mouse": "Electronics", "Bluetooth Speaker": "Electronics",
    "Laptop Stand": "Electronics", "External SSD": "Electronics",
    "Smart Plug": "Electronics", "Screen Protector": "Electronics",
    "Cable Organizer": "Electronics", "Smart TV 55inch": "Electronics",
    "Wireless Charger": "Electronics", "HDMI Cable": "Electronics",
    "Digital Camera": "Electronics", "Electric Fan": "Electronics",
    # Gadgets
    "Fitness Tracker": "Gadgets", "Smart Thermostat": "Gadgets",
    "Robot Vacuum": "Gadgets", "Smart Doorbell": "Gadgets",
    "Dash Cam": "Gadgets", "Action Camera": "Gadgets",
    "Portable Projector": "Gadgets", "E-Reader": "Gadgets",
    "Smart Scale": "Gadgets", "GPS Tracker": "Gadgets",
    # Footwear
    "Running Shoes": "Footwear", "Leather Boots": "Footwear",
    "Canvas Sneakers": "Footwear", "Sandals": "Footwear",
    "Hiking Boots": "Footwear", "Slip-On Loafers": "Footwear",
    "Rain Boots": "Footwear", "Dress Shoes": "Footwear",
    "Flip Flops": "Footwear", "Ankle Boots": "Footwear",
    "Slippers": "Footwear", "Sports Sandals": "Footwear",
    # Clothing
    "Denim Jacket": "Clothing", "Hooded Sweatshirt": "Clothing",
    "Slim Fit Jeans": "Clothing", "Cotton T-Shirt": "Clothing",
    "Wool Sweater": "Clothing", "Jogger Pants": "Clothing",
    "Polo Shirt": "Clothing", "Windbreaker": "Clothing",
    "Cargo Shorts": "Clothing", "Formal Blazer": "Clothing",
    "Winter Coat": "Clothing", "Graphic Tee": "Clothing",
    "Yoga Leggings": "Clothing", "Flannel Shirt": "Clothing",
    "Rain Jacket": "Clothing", "Tank Top": "Clothing",
    "Swim Trunks": "Clothing", "Dress Socks": "Clothing",
    "Thermal Underwear": "Clothing", "Baseball Jersey": "Clothing",
    # Utensils
    "Air Fryer": "Utensils", "Coffee Maker": "Utensils",
    "Blender": "Utensils", "Non-Stick Pan": "Utensils",
    "Dish Rack": "Utensils", "Knife Set": "Utensils",
    "Rice Cooker": "Utensils", "Water Filter": "Utensils",
    "Toaster Oven": "Utensils", "Salad Spinner": "Utensils",
    "Cutting Board": "Utensils", "Electric Kettle": "Utensils",
    "Food Processor": "Utensils", "Mixing Bowl Set": "Utensils",
    "Spice Rack": "Utensils", "Can Opener": "Utensils",
    "Peeler": "Utensils", "Colander": "Utensils",
    "Measuring Cups": "Utensils", "Spatula Set": "Utensils",
    "Pressure Cooker": "Utensils", "Waffle Maker": "Utensils",
    "Egg Boiler": "Utensils", "Juicer": "Utensils",
    # Sports
    "Yoga Mat": "Sports", "Resistance Bands": "Sports",
    "Dumbbells": "Sports", "Jump Rope": "Sports",
    "Foam Roller": "Sports", "Gym Gloves": "Sports",
    "Protein Shaker": "Sports", "Pull-Up Bar": "Sports",
    "Knee Sleeves": "Sports", "Skipping Rope": "Sports",
    "Boxing Gloves": "Sports", "Tennis Racket": "Sports",
    "Basketball": "Sports", "Football": "Sports",
    "Cycling Helmet": "Sports", "Swimming Goggles": "Sports",
    "Badminton Set": "Sports", "Frisbee": "Sports",
    "Water Bottle": "Sports", "Sports Bag": "Sports",
    # Stationery
    "Sticky Notes": "Stationery", "Ballpoint Pens": "Stationery",
    "Spiral Notebook": "Stationery", "Highlighter Set": "Stationery",
    "Desk Planner": "Stationery", "Whiteboard Markers": "Stationery",
    "File Folders": "Stationery", "Stapler": "Stationery",
    "Correction Tape": "Stationery", "Index Cards": "Stationery",
    "Binder Clips": "Stationery", "Gel Pens": "Stationery",
    "Pencil Case": "Stationery", "Ruler": "Stationery",
    "Scissors": "Stationery", "Tape Dispenser": "Stationery",
    "Sketchbook": "Stationery", "Mechanical Pencil": "Stationery",
    "Eraser Set": "Stationery", "Desk Organizer": "Stationery",
    # Bags & Accessories
    "Backpack": "Bags & Accessories", "Tote Bag": "Bags & Accessories",
    "Fanny Pack": "Bags & Accessories", "Laptop Bag": "Bags & Accessories",
    "Crossbody Bag": "Bags & Accessories", "Wallet": "Bags & Accessories",
    "Sunglasses": "Bags & Accessories", "Baseball Cap": "Bags & Accessories",
    "Umbrella": "Bags & Accessories", "Luggage Tag": "Bags & Accessories",
    "Watch Strap": "Bags & Accessories", "Phone Case": "Bags & Accessories",
    "Keychain": "Bags & Accessories", "Travel Pillow": "Bags & Accessories",
    "Duffle Bag": "Bags & Accessories",
    # Toys & Games
    "Jigsaw Puzzle": "Toys & Games", "Playing Cards": "Toys & Games",
    "Chess Set": "Toys & Games", "Building Blocks": "Toys & Games",
    "Rubik's Cube": "Toys & Games", "Board Game": "Toys & Games",
    "Water Gun": "Toys & Games", "Action Figure": "Toys & Games",
    "Remote Control Car": "Toys & Games", "Dart Board": "Toys & Games",
    "Kite": "Toys & Games", "Yo-Yo": "Toys & Games",
    # Food
    "Protein Bar": "Food", "Dark Chocolate": "Food",
    "Honey Jar": "Food", "Trail Mix": "Food",
    "Granola": "Food", "Peanut Butter": "Food",
    "Instant Noodles": "Food", "Canned Tuna": "Food",
    "Olive Oil": "Food", "Hot Sauce": "Food",
    "Pasta": "Food", "Basmati Rice": "Food",
    "Oatmeal": "Food", "Mixed Nuts": "Food",
    "Crackers": "Food", "Cereal": "Food",
    "Jam": "Food", "Maple Syrup": "Food",
    "Soy Sauce": "Food", "Ketchup": "Food",
    # Sweets & Snacks
    "Gummy Bears": "Sweets & Snacks", "Chocolate Chip Cookies": "Sweets & Snacks",
    "Lollipops": "Sweets & Snacks", "Marshmallows": "Sweets & Snacks",
    "Popcorn": "Sweets & Snacks", "Potato Chips": "Sweets & Snacks",
    "Pretzels": "Sweets & Snacks", "Caramel Popcorn": "Sweets & Snacks",
    "Jelly Beans": "Sweets & Snacks", "Brownie Mix": "Sweets & Snacks",
    "Rice Cakes": "Sweets & Snacks", "Fruit Snacks": "Sweets & Snacks",
    # Beverages
    "Sparkling Water": "Beverages", "Oat Milk": "Beverages",
    "Orange Juice": "Beverages", "Apple Juice": "Beverages",
    "Energy Drink": "Beverages", "Coconut Water": "Beverages",
    "Lemonade": "Beverages", "Iced Tea": "Beverages",
    "Sports Drink": "Beverages", "Soda Can": "Beverages",
    "Sparkling Juice": "Beverages", "Almond Milk": "Beverages",
    # Tea & Coffee
    "Green Tea": "Tea & Coffee", "Instant Coffee": "Tea & Coffee",
    "Chamomile Tea": "Tea & Coffee", "Black Tea": "Tea & Coffee",
    "Herbal Tea": "Tea & Coffee", "Matcha Powder": "Tea & Coffee",
    "Coffee Beans": "Tea & Coffee", "Espresso Pods": "Tea & Coffee",
    "Cold Brew Coffee": "Tea & Coffee", "Chai Tea": "Tea & Coffee",
    "Peppermint Tea": "Tea & Coffee", "Decaf Coffee": "Tea & Coffee",
    # Beauty & Personal Care
    "Face Moisturizer": "Beauty & Personal Care", "Sunscreen SPF50": "Beauty & Personal Care",
    "Electric Toothbrush": "Beauty & Personal Care", "Hair Dryer": "Beauty & Personal Care",
    "Shaving Kit": "Beauty & Personal Care", "Lip Balm": "Beauty & Personal Care",
    "Facial Cleanser": "Beauty & Personal Care", "Nail Polish Set": "Beauty & Personal Care",
    "Beard Oil": "Beauty & Personal Care", "Eye Cream": "Beauty & Personal Care",
    "Body Lotion": "Beauty & Personal Care", "Shampoo": "Beauty & Personal Care",
    "Conditioner": "Beauty & Personal Care", "Deodorant": "Beauty & Personal Care",
    "Face Mask": "Beauty & Personal Care", "Perfume": "Beauty & Personal Care",
    "Makeup Brush Set": "Beauty & Personal Care", "Teeth Whitening Kit": "Beauty & Personal Care",
    # Health & Wellness
    "Vitamin C Tablets": "Health & Wellness", "Fish Oil Capsules": "Health & Wellness",
    "Melatonin": "Health & Wellness", "Multivitamin": "Health & Wellness",
    "Zinc Supplements": "Health & Wellness", "Probiotic Capsules": "Health & Wellness",
    "Hand Sanitizer": "Health & Wellness", "First Aid Kit": "Health & Wellness",
    "Heating Pad": "Health & Wellness", "Digital Thermometer": "Health & Wellness",
    "Blood Pressure Monitor": "Health & Wellness", "Pulse Oximeter": "Health & Wellness",
    "Vitamin D": "Health & Wellness", "Omega-3": "Health & Wellness",
    "Collagen Powder": "Health & Wellness",
}