menu_items: list[dict] = [
    {"id": 1, "name": "Spring Rolls", "price": 6.5, "category": "starter"},
    {"id": 2, "name": "Grilled Salmon", "price": 22.0, "category": "main"},
    {"id": 3, "name": "Chocolate Cake", "price": 8.0, "category": "dessert"},
    {"id": 4, "name": "Iced Tea", "price": 3.5, "category": "drink"},
    {"id": 5, "name": "Caesar Salad", "price": 11.0, "category": "starter"},
    {"id": 6, "name": "Garlic Bread", "price": 5.0, "category": "starter"},
    {"id": 7, "name": "Chicken Wings", "price": 9.0, "category": "starter"},
    {"id": 8, "name": "Tomato Soup", "price": 7.0, "category": "starter"},
    {"id": 9, "name": "Beef Burger", "price": 15.0, "category": "main"},
    {"id": 10, "name": "Margherita Pizza", "price": 14.0, "category": "main"},
    {"id": 11, "name": "Spaghetti Carbonara", "price": 16.0, "category": "main"},
    {"id": 12, "name": "Vegetable Stir Fry", "price": 12.0, "category": "main"},
    {"id": 13, "name": "Butter Chicken", "price": 18.0, "category": "main"},
    {"id": 14, "name": "Paneer Tikka Masala", "price": 15.0, "category": "main"},
    {"id": 15, "name": "Fish and Chips", "price": 17.0, "category": "main"},
    {"id": 16, "name": "Cheesecake", "price": 9.0, "category": "dessert"},
    {"id": 17, "name": "Ice Cream Sundae", "price": 7.5, "category": "dessert"},
    {"id": 18, "name": "Brownie", "price": 6.0, "category": "dessert"},
    {"id": 19, "name": "Fruit Salad", "price": 5.5, "category": "dessert"},
    {"id": 20, "name": "Tiramisu", "price": 10.0, "category": "dessert"},
    {"id": 21, "name": "Panna Cotta", "price": 8.5, "category": "dessert"},
    {"id": 22, "name": "Espresso", "price": 3.0, "category": "drink"},
    {"id": 23, "name": "Cappuccino", "price": 4.0, "category": "drink"},
    {"id": 24, "name": "Latte", "price": 4.5, "category": "drink"},
    {"id": 25, "name": "Hot Chocolate", "price": 4.0, "category": "drink"},
    {"id": 26, "name": "Mango Smoothie", "price": 5.5, "category": "drink"},
    {"id": 27, "name": "Lemonade", "price": 3.0, "category": "drink"},
    {"id": 28, "name": "Milkshake", "price": 4.5, "category": "drink"},
    {"id": 29, "name": "Green Tea", "price": 2.5, "category": "drink"},
    {"id": 30, "name": "Sparkling Water", "price": 2.0, "category": "drink"},
]
